### ISSUE TITLE
JsonPointer fragment doesn't work for subfragments

### ISSUE THREAD

**Issue by VisualBean** [LEGO/AsyncAPI.NET#196]
Given a components of
```yaml
messages:
  MyMessage:
    payload:
      type: object
      properties:
        id:
          type: string
```

A reference to `#/components/messsage/MyMessage/payload` should find the right fragment, according to the json-pointer RFC.
However this was never implemented, as we only look up components directly, not sub fragments. (mainly due to the typed nature and the amount of maps that would have to exists to make this possible)
